const { call } = Function.prototype;
export const Number = globalThis.Number;
export const { NaN } = Number;
export const { imul } = Math;
export const { apply, ownKeys, construct } = Reflect;
export const { freeze, setPrototypeOf, getOwnPropertyDescriptor, is } = Object;
export const { sort } = Array.prototype;
export const strCharCodeAt = call.bind(String.prototype.charCodeAt) as (s: string, i: number) => number;
export const Float64Array = globalThis.Float64Array;
export const Uint32Array = globalThis.Uint32Array;
export const Map = globalThis.Map;
export const { set: mapSet, get: mapGet, delete: mapDelete, clear: mapClear } = Map.prototype;
export const WeakMap = globalThis.WeakMap;
export const { set: weakMapSet, get: weakMapGet } = WeakMap.prototype;
export const WeakRef = globalThis.WeakRef;
export const { deref: weakDeref } = WeakRef.prototype;
